version: "3"
services:
  test:
    build: .
    volumes:
      - $PWD:/working
    container_name: Re-Real-estate-transaction-price-prediction
    working_dir: /working
    ports:
      - 8080:8080
    environment:
      - PYTHONPATH=/working
    command: jupyter notebook --notebook-dir=/working --ip=0.0.0.0 --allow-root --no-browser
