seed_everything: &seed 1031

dataset:
  dir: "input/re_real_estate_2020/"
  feature_dir: "features"
  params:

features:
  - Basic
  - LatLon
  - ConcatCategory
  - HandMade

pre_process:
  do: False
  col: "Area"
  xentropy: False

post_process:
  do: False
  col: "Area"

stacking:
  use_org_cols: True
  predictions:
    - 079_lgb_no_divide_no_xentropy
    - 080_lgb_divide_no_xentropy
    - 081_lgb_no_divide_xentropy
    - 082_lgb_divide_xentropy
    - 083_xgb_no_divide_no_xentropy
    - 084_xgb_divide_no_xentropy
    - 085_xgb_no_divide_xentropy
    - 086_xgb_divide_xentropy
    - 087_cat_no_divide_no_xentropy
    - 088_cat_divide_no_xentropy
    - 089_cat_no_divide_xentropy
    - 090_cat_divide_xentropy

av:
  split_params:
    n_splits: 5
    random_state: *seed

  model_params:
    device_type: "gpu"
    gpu_platform_id: 0
    gpu_device_id: 0
    objective: "binary"
    metric: "auc"
    boosting: "gbdt"
    max_depth: 7
    num_leaves: 75
    learning_rate: 0.1
    colsample_bytree: 0.7
    subsample: 0.1
    subsample_freq: 1
    max_bin: 63
    seed: *seed
    feature_fraction_seed: *seed
    drop_seed: *seed
    verbose: -1
    first_metric_only: True

  train_params:
    num_boost_round: 50000
    early_stopping_rounds: 50
    verbose_eval: 200

model:
  name: "lgbm"
  mode: "regression"
  adaptive_learning_rate:
    method: "halve_scheduler_func"
    halve_iter: 200
    warmup_iter: 100
    start_lr: 0.01
    min_lr: 0.01
  model_params:
    device_type: "cpu"
    gpu_platform_id: 0
    gpu_device_id: 0
    objective: "regression"
    metric: "rmse"
    boosting_type: "gbdt"
    max_depth: -1
    num_leaves: 256
    tree_learner: "serial"
    subsample: 0.7
    subsample_freq: 1
    colsample_bytree: 0.5
    max_bin: 255
    seed: *seed
    bagging_seed: *seed
    feature_fraction_seed: *seed
    drop_seed: *seed
    verbose: -1
    first_metric_only: False

  train_params:
    num_boost_round: 10000
    early_stopping_rounds: 100
    verbose_eval: 100

val:
  name: "kfold"
  params:
    n_splits: 5
    random_state: *seed

output_dir: "output"
