dataset:
  dir: "input/atma-cup5/"
  feature_dir: "features"
  params:

features:
  - Basic
  - LabelEncoding
  - Spectrum
  - SpectrumPeaks
  - SpectrumPeaks50Pct

av:
  split_params:
    test_size: 0.33
    random_state: 42

  model_params:
    device_type: "gpu"
    gpu_platform_id: 0
    gpu_device_id: 0
    objective: "binary"
    metric: "auc"
    boosting: "gbdt"
    max_depth: 7
    num_leaves: 75
    learning_rate: 0.01
    colsample_bytree: 0.7
    subsample: 0.1
    subsample_freq: 1
    seed: 111
    feature_fraction_seed: 111
    drop_seed: 111
    verbose: -1
    num_threads: 16
    first_metric_only: True

  train_params:
    num_boost_round: 10000
    early_stopping_rounds: 100
    verbose_eval: 100

model:
  name: "catboost"
  mode: "classification"
  model_params:
    loss_function: "Logloss"
    eval_metric: "AUC"
    task_type: "GPU"
    iterations: 6000
    early_stopping_rounds: 500
    random_seed: 42

  train_params:
    mode: "classification"

val:
  name: "stratified_kfold"
  params:
    target: "target"
    n_splits: 5
    random_state: 1031

output_dir: "output"
