dataset:
  dir: "input/atma-cup5/"
  feature_dir: "features"
  params:

features:
  - Basic
  - LabelEncoding
  - Spectrum
  - SpectrumPeaks
  - SpectrumPeaks50Pct
  - Params

av:
  split_params:
    test_size: 0.33
    random_state: 42

  model_params:
    device_type: "gpu"
    gpu_platform_id: 0
    gpu_device_id: 0
    objective: "binary"
    metric: "auc"
    boosting: "gbdt"
    max_depth: 7
    num_leaves: 75
    learning_rate: 0.01
    colsample_bytree: 0.7
    subsample: 0.1
    subsample_freq: 1
    seed: 111
    feature_fraction_seed: 111
    drop_seed: 111
    verbose: -1
    num_threads: 16
    first_metric_only: True

  train_params:
    num_boost_round: 10000
    early_stopping_rounds: 100
    verbose_eval: 100

model:
  name: "lgbm"
  model_params:
    device_type: "gpu"
    gpu_platform_id: 0
    gpu_device_id: 0
    objective: "binary"
    boosting: "gbdt"
    max_depth: -1
    num_leaves: 2561
    tree_learner: "serial"
    learning_rate: 0.01
    bagging_fraction: 1
    bagging_freq: 10
    feature_fraction: 1
    max_bin: 255
    lambda_l1: 2.0
    lambda_l2: 1.0
    is_unbalance: True
    seed: 71
    bagging_seed: 71
    feature_fraction_seed: 71
    drop_seed: 71
    verbose: -1
    num_threads: 16
    first_metric_only: True

  train_params:
    num_boost_round: 10000
    early_stopping_rounds: 200
    verbose_eval: 50


val:
  name: "stratified_kfold"
  params:
    target: "target"
    n_splits: 5
    random_state: 1031

output_dir: "output"
