dataset:
  dir: "input/atma-cup5/"
  feature_dir: "features"
  params:

features:
  - Basic
  - LabelEncoding
  - Spectrum
  - SpectrumPeaks
  - SpectrumPeaks50Pct
  - Params
av:
  split_params:
    test_size: 0.33
    random_state: 42

  model_params:
#    device_type: "gpu"
#    gpu_platform_id: 0
#    gpu_device_id: 0
    objective: "binary"
    metric: "auc"
    boosting: "gbdt"
    max_depth: 7
    num_leaves: 75
    learning_rate: 0.01
    colsample_bytree: 0.7
    subsample: 0.1
    subsample_freq: 1
    seed: 111
    feature_fraction_seed: 111
    drop_seed: 111
    verbose: -1
    num_threads: 16
    first_metric_only: True

  train_params:
    num_boost_round: 10000
    early_stopping_rounds: 100
    verbose_eval: 100

model:
  name: "rgf"
  model_params:
    n_estimators: 500
    max_depth: 6
    max_leaf: 50
    tree_gain_ratio: 1.0
    min_samples_leaf: 5
    l1: 1.0
    l2: 1000.0
    opt_algorithm: "rgf"
    learning_rate: 0.001
    max_bin: 255
    min_child_weight: 5.0
    data_l2: 2.0
    sparse_max_features: 80000
    sparse_min_occurences: 5
    n_jobs: -1
    verbose: 1

  train_params:
    mode: "classification"


val:
  name: "stratified_kfold"
  params:
    target: "target"
    n_splits: 5
    random_state: 1031

output_dir: "output"
