dataset:
  dir: "input/m5-forecasting-accuracy/"
  feature_dir: "features"
  params:

features:
  - Basic
  - Label_Encoding
av:
  split_params:
    test_size: 0.33
    random_state: 42

  model_params:
    objective: "binary"
    metric: "auc"
    boosting: "gbdt"
    max_depth: 7
    num_leaves: 75
    learning_rate: 0.01
    colsample_bytree: 0.7
    subsample: 0.1
    subsample_freq: 1
    seed: 111
    feature_fraction_seed: 111
    drop_seed: 111
    verbose: -1
    first_metric_only: True

  train_params:
    num_boost_round: 1000
    early_stopping_rounds: 100
    verbose_eval: 100

model:
  name: "lgbm"
  mode: "regression"
  model_params:
    objective: "regression"
    metric: "rmse"
    boosting_type: "gbdt"
    max_depth: -1
    num_leaves: 2561
    tree_learner: "serial"
    learning_rate: 0.07 # 0.1じゃ大きいし0.05じゃ小さいかなという気持ち
    subsample: 0.7
    subsample_freq: 1
    colsample_bytree: 0.5
    max_bin: 255
    seed: 71
    bagging_seed: 71
    feature_fraction_seed: 71
    drop_seed: 71
    verbose: 1
    num_threads: 4
    first_metric_only: False

  train_params:
    num_boost_round: 10000
    early_stopping_rounds: 100
    verbose_eval: 100


val:
  name: "date_hold_out"
  params:
    date_col: "date"
    threshold_date: "2016-03-24"

output_dir: "output"
